enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  2e6b2eee-3fb4-42c7-b0a3-7ead13309152:
    enabledByDefault: true
    hasUrls: true
    template: blog\index
    uriFormat: blog
type: single
